# Header
menu:
  Home: /
  Archives: /archives

# Read More text
excerpt_link: Read More

# Disqus Comments Shortname
disqus_shortname: selink

# Google Analytics Tracking ID
google_analytics:

# Widgets List
widgets:
  about: #This blog is based off the Tailwind components template.
  tags: true
  
  
unfaedah:
  Logo: '/drink.svg'
  Name: 'Wong Sepele'
  Title: 'Unfaedah'
  Cover: '/andrea-de-santis-0pRt9f8NM44-unsplash.jpg'
  cLight: 'bg-coolGray-100'
  cDark: 'bg-gray-600'